services:
  - type: web
    name: jobtrackr-backend
    env: docker
    region: oregon
    plan: free
    dockerContext: .
    envVars:
      - key: APP_NAME
        value: JobTrackr
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:base64:YourBase64KeyWillBeGeneratedByRender
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://jobtrackr-backend.onrender.com
      
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d4cdu0a4d50c73d519r0-a.oregon-postgres.render.com
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: jobtrackr_8jpn
      - key: DB_USERNAME
        value: jobtrackr_8jpn_user
      - key: DB_PASSWORD
        value: B6vbgGyjzJTvJNIj2Dpy0hhdPCS01puz
      
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
      - key: BROADCAST_CONNECTION
        value: log
      - key: FILESYSTEM_DISK
        value: local
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        value: kamdem.guy@institutsaintjean.org
      - key: MAIL_PASSWORD
        value: osurrusawvgooxam
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: kamdem.guy@institutsaintjean.org
      - key: MAIL_FROM_NAME
        value: JobTrackr
      
      - key: SANCTUM_STATEFUL_DOMAINS
        value: jobtrackr-backend.onrender.com,localhost,127.0.0.1
      - key: SESSION_DOMAIN
        value: ""
      - key: CORS_ALLOWED_ORIGINS
        value: https://jobtrackr-backend.onrender.com,http://localhost:5173
      - key: FRONTEND_URL
        value: https://jobtrackr-backend.onrender.com
